energy_consumptions = [
    'z1_AC1(kW)',
    'z1_AC2(kW)',
    'z1_AC3(kW)',
    'z1_AC4(kW)',
    'z1_Light(kW)',
    'z1_Plug(kW)',
    'z2_AC1(kW)',
    'z2_Light(kW)',
    'z2_Plug(kW)',
    'z3_Light(kW)',	
    'z3_Plug(kW)',
    'z4_AC1(kW)',
    'z4_Light(kW)',
    'z4_Plug(kW)',
    'z5_AC1(kW)',
    'z5_Light(kW)',
    'z5_Plug(kW)'
    ]